export default {
  header: {
    height: 90,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderStyle: 'dashed',
    borderColor: '#e6e6e6',
  },
  listContainer: {
    borderWidth: 4,
    borderStyle: 'dashed',
    borderColor: '#ef6000',
  },
  rowItem: {
    height: 80,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-color 800ms',
  },
  footer: {
    height: 90,
    padding: 20,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderStyle: 'dashed',
    borderColor: '#e6e6e6',
  },
  footerInput: {
    flex: 1,
    borderColor: '#ff6000',
    borderWidth: 2,
    borderStyle: 'solid',
  },
};
